/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package discretas;

import javax.swing.JOptionPane;

/**
 *
 * @author Yfmay
 */
public class View extends javax.swing.JFrame {

   private String[] vector;
    private int[][] grafo;
     
    public View(String[] vector, int[][] grafo){
        this.vector = vector;
        initComponents();
        this.grafo = grafo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jM = new javax.swing.JButton();
        jBu = new javax.swing.JButton();
        jBe = new javax.swing.JButton();
        jV = new javax.swing.JButton();
        jS = new javax.swing.JButton();
        jCh = new javax.swing.JButton();
        jBa = new javax.swing.JButton();
        jG = new javax.swing.JButton();
        jplay = new javax.swing.JButton();
        jVi = new javax.swing.JButton();
        bv = new javax.swing.JLabel();
        gaba = new javax.swing.JLabel();
        gbu2 = new javax.swing.JLabel();
        bub1 = new javax.swing.JLabel();
        veb1 = new javax.swing.JLabel();
        bema1 = new javax.swing.JLabel();
        chama1 = new javax.swing.JLabel();
        sacha1 = new javax.swing.JLabel();
        sama1 = new javax.swing.JLabel();
        buma1 = new javax.swing.JLabel();
        busa1 = new javax.swing.JLabel();
        visa1 = new javax.swing.JLabel();
        basa1 = new javax.swing.JLabel();
        gavi1 = new javax.swing.JLabel();
        gavi2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jM.setText("Málaga");
        jPanel1.add(jM, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 100, 30));

        jBu.setText("Bucaramanga");
        jBu.setFocusPainted(false);
        jBu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuActionPerformed(evt);
            }
        });
        jPanel1.add(jBu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 140, 40));

        jBe.setText("Berlín");
        jBe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeActionPerformed(evt);
            }
        });
        jPanel1.add(jBe, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 80, 40));

        jV.setText("Vetas");
        jV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVActionPerformed(evt);
            }
        });
        jPanel1.add(jV, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 30, 90, 40));

        jS.setText("San Gil");
        jPanel1.add(jS, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 220, 100, 30));

        jCh.setText("Charalá");
        jPanel1.add(jCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 80, 40));

        jBa.setText("Barichara");
        jBa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaActionPerformed(evt);
            }
        });
        jPanel1.add(jBa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 90, 40));

        jG.setText("Galán");
        jG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGActionPerformed(evt);
            }
        });
        jPanel1.add(jG, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 230, 100, 30));

        jplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jplay.setText("Iniciar");
        jplay.setRequestFocusEnabled(false);
        jplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplayMouseClicked(evt);
            }
        });
        jPanel1.add(jplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 130, 60));

        jVi.setText("Villanueva");
        jPanel1.add(jVi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 100, 40));

        bv.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        bv.setText("172");
        jPanel1.add(bv, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        gaba.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        gaba.setText("58");
        jPanel1.add(gaba, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        gbu2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        gbu2.setText("219");
        jPanel1.add(gbu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        bub1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        bub1.setText("104");
        jPanel1.add(bub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        veb1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        veb1.setText("79");
        jPanel1.add(veb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 20, -1));

        bema1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        bema1.setText("273");
        jPanel1.add(bema1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, -1));

        chama1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        chama1.setText("402");
        jPanel1.add(chama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        sacha1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        sacha1.setText("50");
        jPanel1.add(sacha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        sama1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        sama1.setText("360");
        jPanel1.add(sama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        buma1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        buma1.setText("320");
        jPanel1.add(buma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        busa1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        busa1.setText("161");
        jPanel1.add(busa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        visa1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        visa1.setText("32");
        jPanel1.add(visa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        basa1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        basa1.setText("35");
        jPanel1.add(basa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        gavi1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        gavi1.setText("23");
        jPanel1.add(gavi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        gavi2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        gavi2.setText("85");
        jPanel1.add(gavi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/discretas/fondo/Fondo1_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 660, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBuActionPerformed

    private void jBeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBeActionPerformed

    private void jVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jVActionPerformed

    private void jBaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBaActionPerformed

    private void jGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jGActionPerformed

    private void jplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplayMouseClicked

        CaminoHamiltoniano h = new CaminoHamiltoniano(grafo);
        String opcion = JOptionPane.showInputDialog(this,"Seleccione el pueblo de salida","Pueblos",1,null,vector,vector[0]).toString();
        h.encontrarCaminoHamiltoniano(busquedaSecuencial(vector,opcion), vector);
        JOptionPane.showMessageDialog(this,h.toString(vector) + "\n\n" + h.conLluvia(vector),"Ruta Generada",1);

    }//GEN-LAST:event_jplayMouseClicked

    public int busquedaSecuencial(String[] vector, String x){
        boolean found = false;
        
        for(int i=0; i< vector.length && found==false; i++){
            if(x.equals(vector[i])){
                found = true;
                return i;
            }
        }
        return -1;
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel basa1;
    private javax.swing.JLabel bema1;
    private javax.swing.JLabel bub1;
    private javax.swing.JLabel buma1;
    private javax.swing.JLabel busa1;
    private javax.swing.JLabel bv;
    private javax.swing.JLabel chama1;
    private javax.swing.JLabel gaba;
    private javax.swing.JLabel gavi1;
    private javax.swing.JLabel gavi2;
    private javax.swing.JLabel gbu2;
    private javax.swing.JButton jBa;
    private javax.swing.JButton jBe;
    private javax.swing.JButton jBu;
    private javax.swing.JButton jCh;
    private javax.swing.JButton jG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jM;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jS;
    private javax.swing.JButton jV;
    private javax.swing.JButton jVi;
    private javax.swing.JButton jplay;
    private javax.swing.JLabel sacha1;
    private javax.swing.JLabel sama1;
    private javax.swing.JLabel veb1;
    private javax.swing.JLabel visa1;
    // End of variables declaration//GEN-END:variables
}
